### ISSUE TITLE
Question: May I fork this project and translate it into Chinese?

### ISSUE THREAD

**Issue by fanjieqi** [khusnetdinov/ruby.fundamental#2]
Hey, buddy, I've read part of this project, I found it's very useful for the beginning and further study of a ruby-coder. May I fork it and translate it into Chinese ?

**Comment by khusnetdinov** [comment]
Sure. Only just create link for original source.

**Comment by khusnetdinov** [comment]
After You create repo give me a link a will add it to my repo for people who want read in Chinese.

**Comment by fanjieqi** [comment]
The link for original source will absolutely be added.
Thanks~
